
fit:
  trainer:
    max_epochs: 100
    gradient_clip_val: 4.0
    gradient_clip_algorithm: "norm"
    callbacks:
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          patience: 5
          monitor: val_loss
      - class_path: lightning.pytorch.callbacks.ModelCheckpoint
        init_args:
          dirpath: ./cache/savedmodels/
          save_last: True

  model:
    latent_dim: 200
    conv_depth: 2
    fc_depth: 1
    dropout: null
    batchnorm: False