
fit:
  trainer:
    max_epochs: 100
    callbacks:
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          patience: 5
          monitor: val_loss
      - class_path: lightning.pytorch.callbacks.ModelCheckpoint
        init_args:
          dirpath: ./cache/savedmodels/
          save_last: True