# lightning.pytorch==2.4.0
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: false
  callbacks:
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: val_loss
      min_delta: 0.0
      patience: 5
      verbose: false
      mode: min
      strict: true
      check_finite: true
      stopping_threshold: null
      divergence_threshold: null
      check_on_train_epoch_end: null
      log_rank_zero_only: false
  - class_path: ptbxlae.modeling.NeptuneUploadingModelCheckpoint
    init_args:
      dirpath: ./cache/savedmodels/
      filename: synthetic-mc-{epoch:03d}-{val_loss:.6f}
      monitor: val_loss
      verbose: false
      save_last: null
      save_top_k: 1
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
      enable_version_counter: true
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: 00:47:00:00
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: 4.0
  gradient_clip_algorithm: norm
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  class_path: ptbxlae.modeling.convolutionalVAE.ConvolutionalEcgVAE
  init_args:
    lr: 4.7491754446145785e-05
    kernel_size: 7
    latent_dim: 100
    seq_len: 1000
    n_channels: 12
    conv_depth: 3
    fc_depth: 2
    fc_scale_factor: 4
    batchnorm: false
    dropout: null
    loss:
      class_path: ptbxlae.modeling.SumReducingSoftDTWLoss
      init_args:
        gamma: 1
        normalize: false
        dist_func: null
data:
  class_path: ptbxlae.dataprocessing.dataModules.SyntheticDM
  init_args:
    root_folder: ./data
    batch_size: 2
    examples_per_epoch: 3200.0
    duration_s: 10
    sampling_rate_hz: 100
optimizer: null
lr_scheduler: null
ckpt_path: null
