trainer:
  max_epochs: 1000
  gradient_clip_val: 4.0
  gradient_clip_algorithm: "norm"
  devices: 1
  num_nodes: 1
  logger:
    - class_path: lightning.pytorch.loggers.NeptuneLogger
      init_args:
        project: isears/ptbxlae
        log_model_checkpoints: False
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
    - class_path: ptbxlae.modeling.NeptuneUploadingModelCheckpoint
      init_args:
        log_sample_reconstructions: False
        save_top_k: 1
        monitor: val_loss
        mode: min
        dirpath: ./cache/savedmodels/
        filename: best-{epoch:04d}-{val_loss:.6f}