
fit:
  trainer:
    max_epochs: 100
    gradient_clip_val: 4.0
    gradient_clip_algorithm: "norm"
    callbacks:
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          patience: 5
          monitor: val_loss
      - class_path: lightning.pytorch.callbacks.ModelCheckpoint
        init_args:
          save_top_k: 1
          monitor: val_loss
          mode: min
          dirpath: ./cache/savedmodels/
          filename: mccss-{epoch:03d}-{val_loss:.6f}

  model:
    class_path: ptbxlae.modeling.convolutionalVAE.ConvolutionalEcgVAE
    init_args:
      seq_len: 500
      latent_dim: 100
      conv_depth: 2
      fc_depth: 2
      kernel_size: 5
      fc_scale_factor: 2
      dropout: null
      batchnorm: False
      lr: 4.7491754446145785e-05
      n_channels: 12
  data:
    class_path: ptbxlae.dataprocessing.dataModules.PtbxlSmallSigDM
    init_args:
      batch_size: 8
      seq_len: 500
