
fit:
  trainer:
    max_epochs: 100
    gradient_clip_val: 4.0
    gradient_clip_algorithm: "norm"
    callbacks:
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          patience: 5
          monitor: val_loss
      - class_path: lightning.pytorch.callbacks.ModelCheckpoint
        init_args:
          save_top_k: 1
          monitor: val_loss
          mode: min
          dirpath: ./cache/savedmodels/
          filename: mccssfc-{epoch:03d}-{val_loss:.6f}

  model:
    class_path: ptbxlae.modeling.feedForwardVAE.SingleChannelFFNNVAE
    init_args:
      seq_len: 500
      latent_dim: 100
  data:
    class_path: ptbxlae.dataprocessing.dataModules.PtbxlSmallSigDM
    init_args:
      batch_size: 8
      seq_len: 500
      single_channel: True
