# Achieved 0.00732603 validation MSE during hyperparameter tuning
model:
  class_path: ptbxlae.modeling.convolutionalVAE.ConvolutionalEcgVAE
  init_args:
    latent_dim: 100
    conv_depth: 5
    fc_depth: 1
    fc_scale_factor: 4
    kernel_size: 15
    batchnorm: True
    dropout: null
    lr: 0.0003016868024815632
    n_channels: 12
    seq_len: 1000

data:
  class_path: ptbxlae.dataprocessing.dataModules.DefaultDM
  init_args:
    ds:
      class_path: ptbxlae.dataprocessing.ptbxlDS.PtbxlDS
      init_args:
        lowres: True
    batch_size: 213
