
fit:
  trainer:
    max_epochs: 500
    gradient_clip_val: 4.0
    gradient_clip_algorithm: "norm"
    callbacks:
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          patience: 5
          monitor: val_loss
      - class_path: lightning.pytorch.callbacks.ModelCheckpoint
        init_args:
          dirpath: ./cache/savedmodels/
          save_last: True

  model:
    class_path: ptbxlae.modeling.multiCycleConv.RpeakVAE
    init_args:
      latent_dim: 10
      conv_depth: 2
      fc_depth: 1
      kernel_size: 7
      dropout: null
      batchnorm: False
      lr: 1e-3
  data:
    class_path: ptbxlae.dataprocessing.dataModules.PtbxlSigWithRpeaksDM
    init_args:
      batch_size: 32