
fit:
  trainer:
    max_epochs: 500
    gradient_clip_val: 4.0
    gradient_clip_algorithm: "norm"
    callbacks:
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          patience: 5
          monitor: val_loss
      - class_path: lightning.pytorch.callbacks.ModelCheckpoint
        init_args:
          save_top_k: 1
          monitor: val_loss
          mode: min
          dirpath: ./cache/savedmodels/
          filename: rpeaks-{epoch:03d}-{val_loss:.6f}

  model:
    class_path: ptbxlae.modeling.convolutionalVAE.RpeakAE
    init_args:
      conv_depth: 2
      fc_depth: 1
      kernel_size: 7
      lr: 1e-3
  data:
    class_path: ptbxlae.dataprocessing.dataModules.PtbxlSigWithRpeaksDM
    init_args:
      batch_size: 32