
fit:
  trainer:
    max_epochs: 100
    gradient_clip_val: 4.0
    gradient_clip_algorithm: "norm"
    callbacks:
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          patience: 5
          monitor: val_loss
      - class_path: lightning.pytorch.callbacks.ModelCheckpoint
        init_args:
          dirpath: ./cache/savedmodels/
          save_last: True

  model:
    class_path: ptbxlae.modeling.convolutionalVAE.ConvolutionalEcgVAE
    init_args:
      latent_dim: 40
      conv_depth: 2
      fc_depth: 1
      dropout: null
      batchnorm: False
  data:
    class_path: ptbxlae.dataprocessing.dataModules.SingleCycleCachedDM
    init_args:
      batch_size: 32