model:
  class_path: ptbxlae.modeling.convolutionalVAE.ConvolutionalEcgVAE
  init_args:
    latent_dim: 100
    conv_depth: 5
    fc_depth: 1
    fc_scale_factor: 4
    kernel_size: 15
    dropout: null
    batchnorm: True
    lr: 0.00024422008762451405
    n_channels: 12
    seq_len: 1000
    loss: null

data:
  class_path: ptbxlae.dataprocessing.dataModules.DefaultDM
  init_args:
    ds:
      class_path: ptbxlae.dataprocessing.nkSyntheticDS.NkSyntheticDS
      init_args:
        examples_per_epoch: 2200
    batch_size: 220