fit:
  trainer:
    max_time: 00:47:00:00
    gradient_clip_val: 4.0
    gradient_clip_algorithm: "norm"
    logger:
      - class_path: lightning.pytorch.loggers.NeptuneLogger
        init_args:
          project: isears/ptbxlae
          log_model_checkpoints: False
        dict_kwargs:
          tags:
            - synthetic-pretraining
            - full-10s
            - single-channel
    callbacks:
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          patience: 10
          monitor: val_loss
      - class_path: ptbxlae.modeling.NeptuneUploadingModelCheckpoint
        init_args:
          save_top_k: 1
          monitor: val_loss
          mode: min
          dirpath: ./cache/savedmodels/
          filename: synthetic-{epoch:03d}-{val_loss:.6f}

  model:
    class_path: ptbxlae.modeling.convolutionalVAE.ConvolutionalEcgVAE
    init_args:
      latent_dim: 40
      conv_depth: 3
      fc_depth: 2
      kernel_size: 7
      dropout: null
      batchnorm: False
      lr: 4.7491754446145785e-05
      n_channels: 1
      seq_len: 1000
  data:
    class_path: ptbxlae.dataprocessing.dataModules.SingleChannelSyntheticDM
    init_args:
      batch_size: 32
      examples_per_epoch: 3200