model:
  class_path: ptbxlae.modeling.maskedPretrainingTransformer.MaskedPretrainingTransformerClassifier
  init_args:
    lr: 1e-4
    freeze_base_model: False
    n_classes: 44

data:
  class_path: ptbxlae.dataprocessing.dataModules.DefaultDM
  init_args:
    batch_size: 32
    ds:
      class_path: ptbxlae.dataprocessing.ptbxlDS.PtbxlMultilabeledDS
      init_args:
        lowres: True
        return_labels: True