model:
  class_path: ptbxlae.modeling.ekgTransformer.RegressionTransformerLM
  init_args:
    lr: 1e-4
    n_outputs: 20
    
data:
  class_path: ptbxlae.dataprocessing.dataModules.DefaultDM
  init_args:
    batch_size: 32
    ds:
      class_path: ptbxlae.dataprocessing.mimicDS.MimicDS
      init_args:
        mimic_connector:
          class_path: ptbxlae.dataprocessing.mimicDS.MimicSqlConnector
          init_args:
            database: mimiciv
            user: readonly
