model:
  class_path: ptbxlae.modeling.ekgTransformer.ClassificationTransformerLM
  init_args:
    lr: 1e-4
    n_labels: 44
    
data:
  class_path: ptbxlae.dataprocessing.dataModules.DefaultDM
  init_args:
    batch_size: 32
    ds:
      class_path: ptbxlae.dataprocessing.ptbxlDS.PtbxlMultilabeledDS
      init_args:
        lowres: True
